spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/IncidentApp_db
    username: springuser
    password: system
  jpa:
    hibernate:
      ddl-auto: update